### ISSUE TITLE
Modify Json

### ISSUE THREAD

**Issue by melitina915** [PYI-Solux/Spring_Backend#16]
## ✅ Checklist
- [ ] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성

## ✏ Description
- JSON 형식 수정

## 📋 TODO
- [ ] JSON 수정 완료
